# Generated by Django 6.0 on 2026-01-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='slug',
            new_name='brand_slug',
        ),
    ]
