# Generated by Django 6.0 on 2026-01-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_contact_email_alter_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(max_length=200)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('total', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='order_images')),
                ('phone', models.CharField(max_length=200)),
                ('full_address', models.CharField(max_length=200)),
                ('is_pay', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('order_notes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
